function update(self, dt)
	self.collision_id = nil
end


function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		if not self.collision_id or go.get_position(self.collision_id).z < message.other_position.z then
			self.collision_id = message.other_id
		end
	end

	if message_id == hash("gameOver") then
		msg.post(".", "release_input_focus")
	elseif message_id == hash("takeInput") then
		msg.post(".", "acquire_input_focus")
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") then

		local action_pos = vmath.vector3(action.x, action.y, 0)
		go.set_position(action_pos)

		if action.pressed then
			msg.post("#collisionobject", "enable")

		elseif action.released and self.collision_id then
			msg.post("#collisionobject", "disable")
			msg.post(self.collision_id, "openOne")
		end

	end
end